import {COINS,POLICY,validateLimits,selection,makePlan,DAY} from './policy.mjs';
import {decide} from './decision.mjs';
const futures=/(^|\/)futures(\/|$)/.test(location.pathname)||new URLSearchParams(location.search).get('mode')==='futures';
const exchange=futures?'bitget':'korbit',currency=futures?'USDT':'KRW',name=futures?'비트겟 USDT 무기한 선물':'코빗 원화 현물';
const root=document.createElement('section');root.id='trade-console';root.setAttribute('aria-label','D−5 80% 거래 관리');
const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('./dashboard.css',import.meta.url);document.head.append(css);
(document.querySelector('header')||document.body.firstElementChild).insertAdjacentElement('afterend',root);
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,n=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString('ko-KR',{maximumFractionDigits:n}):'—';
const percent=v=>v==null?'—':(v*100).toFixed(1)+'%';
const table=(headers,rows)=>`<div class="tc-scroll"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
root.innerHTML=`<div class="tc-kicker">COIN SIGNAL · V2.01</div><h2>${name} · D−5 / 80%</h2><p class="tc-sub">과거 유사 사례 30개 이상 · 확률 80% 이상 · 가격 등간격 5분할 · 전체 + 종목별 한도</p>
<div class="tc-grid"><div class="tc-card"><small>거래소 / 통화</small><strong>${futures?'Bitget / USDT':'Korbit / KRW'}</strong></div><div class="tc-card"><small>현재가</small><strong id="tc-price">—</strong></div><div class="tc-card"><small>5일 내 신호 확률</small><strong id="tc-prob">계산 대기</strong></div><div class="tc-card"><small>실행 상태</small><strong id="tc-mode">미연결</strong></div></div>
<div class="tc-row"><label>종목<select id="tc-coin">${COINS.map(c=>`<option>${c}</option>`).join('')}</select></label><label>전략<select id="tc-strategy">${Array.from({length:futures?5:3},(_,i)=>`<option value="${i+1}">MACD ${i+1}</option>`).join('')}</select></label><button id="tc-load" class="tc-primary">거래소 시세·신호 조회</button></div>
<p class="tc-sub">${futures?'단방향·격리, 거래소 레버리지 2배 설정을 확인합니다. MACD 5는 위 골든 롱 200%·위 데드 롱 50%·아래 골든 롱 50%·아래 데드 숏 200%입니다.':'현물 MACD 1~3을 지원합니다. 매도는 보유 수량 이내이며, 숏·차입 주문은 만들지 않습니다.'}</p>
<h3>투자 한도</h3><div class="tc-row"><label>계좌 전체 한도 (${currency})<input id="tc-total" type="number" min="0" step="any" placeholder="필수 입력"></label><label>선택 종목 한도 (${currency})<input id="tc-cap" type="number" min="0" step="any" placeholder="필수 입력"></label><button id="tc-save">한도 저장</button></div><p class="tc-sub">보유 자산 평가금액 + 미체결 신규 주문 금액을 합산합니다. ${futures?'선물 한도는 증거금이 아닌 포지션 명목금액입니다. MACD 5의 기준 운용금은 종목 한도의 최대 ½로 제한합니다. ':''}가격 상승으로 한도를 넘으면 신규 투자를 제한하며, 초과분을 자동 추가 투자하지 않습니다. 한도 초과만으로 강제 매도하지 않습니다. 코빗 KRW와 비트겟 USDT 한도는 계좌별로 관리합니다.</p><div id="tc-limits"></div>
<details open><summary>주문 미리보기</summary><p class="tc-sub">D−5~D−1은 완성 일봉마다 미체결 취소를 확인한 후 잔량을 5개 등간격 지정가로 재배치합니다. 예측 날짜만으로 강제 체결하지 않으며, 실제 신호 확정 후 잔량 완료를 시도합니다. 완료 주문은 가격 제한 IOC를 사용하므로 거래소 장애·유동성 부족·최소 주문 금액으로 잔량이 남으면 상태에 표시됩니다.</p><div class="tc-row"><label>모의 계좌 평가액 (${currency})<input id="tc-equity" type="number" min="0" step="any" placeholder="모의 계산용"></label><button id="tc-preview">모의 계좌로 계산</button><button id="tc-private-preview" disabled>실계좌 잔고로 미리보기</button></div><div id="tc-plan"></div></details>
<details><summary>실행 서버 연결 · 자동매매 관리</summary><p class="tc-sub">거래소 키는 고정 IP 실행 서버에만 보관합니다. 이 입력칸은 앱 관리자 접속 토큰이며 거래소 API 키를 입력하는 곳이 아닙니다. 실주문은 서버 연결·한도 저장·실계좌 미리보기 후 시작할 수 있습니다.</p><div class="tc-row"><label>관리자 접속 토큰<input id="tc-token" type="password" autocomplete="off" placeholder="서버 관리자 토큰"></label><button id="tc-login">접속</button><button id="tc-logout">로그아웃</button><button id="tc-refresh">실행 상태 조회</button></div><p id="tc-auto-state" role="status">자동매매 상태: 관리자 접속 필요</p><div class="tc-row"><button id="tc-auto-on" disabled>이 거래소 자동매매 ON</button><button id="tc-auto-off" class="tc-danger" disabled>이 거래소 전체 OFF · 미체결 취소</button></div><p class="tc-sub">ON은 실행 허용입니다. 종목별 실계좌 미리보기 후 시작해야 주문합니다. OFF는 이 거래소의 모든 등록 종목을 중지하며 보유 포지션은 유지합니다. 다시 ON으로 바꾸어도 중지한 종목은 자동 재시작하지 않습니다.</p><div class="tc-row"><button id="tc-arm" class="tc-danger" disabled>자동매매 시작</button><button id="tc-stop" disabled>선택 종목 중지 · 미체결 취소</button></div><p class="tc-sub">중지는 앱이 등록한 미체결 주문을 취소합니다. 이미 보유한 포지션은 유지됩니다. 서버에서 전체 실행을 끄더라도 잔존 주문 취소 상태를 확인하세요.</p><div id="tc-account"></div></details>
<details><summary>기존 앱 자료 · D−5 / 80% 검증 결과</summary><p class="tc-warn">아래 수익률은 2017~2026년 앱 내장 자료를 이용한 연구 결과입니다. 거래소 전환·투자 한도·실제 펀딩비·청산 규칙을 적용한 실계좌 수익률이 아닙니다.</p><div id="tc-comparison">불러오는 중</div></details>
<p id="tc-message" class="tc-status" role="status" aria-live="polite">실행 서버 상태를 확인하고 있습니다.</p>`;
const $=s=>root.querySelector(s),coinFromPage=window.__COIN_DATA__?.symbol;
$('#tc-coin').value=COINS.includes(coinFromPage)?coinFromPage:'BTC';$('#tc-strategy').value=futures?'5':'3';
let comparison=[];
function paintComparison(){const c=selected().coin;$('#tc-comparison').innerHTML=table([c+' 전략','확정 신호 기준','D−5 / 80%','차이 (%p)'],comparison.filter(r=>r.coin===c&&(futures||r.n<=3)).map(r=>['MACD '+r.n,fmt(r.baseline*100)+'%',fmt(r.updated*100)+'%',fmt((r.updated-r.baseline)*100)]));}
let revision=0;
let market=null,candles=[],decision=null,quote=null,loggedIn=false,server=null,busy=false;
const storageKey='exchange-limits-v2:'+exchange;
let limits;try {limits=validateLimits(JSON.parse(localStorage.getItem(storageKey)));}catch{limits={total:'',symbols:{}};}
function selected(){return selection(exchange,$('#tc-coin').value,Number($('#tc-strategy').value));}
function message(text){$('#tc-message').textContent=text;}
function invalidate(){revision++;quote=null;$('#tc-arm').disabled=true;$('#tc-plan').replaceChildren();}
function paintLimits(){ $('#tc-total').value=limits.total;$('#tc-cap').value=limits.symbols[$('#tc-coin').value]||'';$('#tc-limits').innerHTML=table(['저장된 종목','포지션 금액 한도 ('+currency+')'],Object.entries(limits.symbols).map(([c,v])=>[c,fmt(v)])); }
paintLimits();
async function json(url,options){const r=await fetch(url,options),data=await r.json();if(!r.ok||data.error)throw Error(data.error||'조회 실패');return data;}
async function command(action,extra={}) {return json('/api/trading',{method:'POST',headers:{'Content-Type':'application/json','X-Trading-UI':'1'},body:JSON.stringify({action,...selected(),...extra})});}
async function run(fn){if(busy)return;busy=true;root.setAttribute('aria-busy','true');try{await fn();}catch(e){message(e.message);quote=null;$('#tc-arm').disabled=true;}finally{busy=false;root.removeAttribute('aria-busy');}}
function planView(p,live){$('#tc-plan').innerHTML=`<p>${live?'실계좌':'모의 계좌'} · ${esc(p.decision.kind)} · 목표 ${percent(p.decision.target)} · 기준 운용금 ${fmt(p.budget)} ${currency} · 가격 간격 ${fmt(p.step,8)}</p><p class="tc-sub">${esc(p.phase)} · 현 보유 ${fmt(p.currentQty,8)} · 목표 ${fmt(p.targetQty,8)} · 현재 사용 ${fmt(p.used)} ${currency}</p>${table(['분할','방향','수량','지정가','체결 정책'],p.orders.map(o=>[o.split,o.side==='buy'?'매수':'매도',o.qty,o.price,o.reduceOnly?'포지션 감소 / '+o.timeInForce:o.timeInForce]))}<p class="tc-warn">${esc(p.reason||'주문 접수 후 실제 체결 수량을 확인합니다. 접수만으로 완료 처리하지 않습니다.')}</p>`;}
async function status(){invalidate();server=await command('status');loggedIn=true;$('#tc-auto-state').textContent='자동매매 '+(server.automationOn?'ON':'OFF')+' · 서버 실행 '+(server.serverEnabled?'허용':'차단')+' · '+(server.demo?'데모':'실계좌');$('#tc-auto-on').disabled=!server.serverEnabled||server.automationOn;$('#tc-auto-off').disabled=false;$('#tc-mode').textContent=server.enabled?(server.demo?'거래소 데모':'실주문 준비'):'실행 꺼짐';$('#tc-private-preview').disabled=false;$('#tc-stop').disabled=false;$('#tc-account').innerHTML=table(['종목','전략','상태','최근 확인'],server.campaigns.map(c=>[c.coin,'MACD '+c.strategy,c.status,c.error||c.lastDecision?.explanation||'대기']))+table(['시각','종목','주문 상태','체결 수량'],server.orders.slice(-20).map(o=>[new Date(o.at).toLocaleString('ko-KR'),o.coin,o.status,o.filled||0]));if(server.limits){limits=validateLimits(server.limits);localStorage.setItem(storageKey,JSON.stringify(limits));paintLimits();}return server;}
$('#tc-save').onclick=()=>run(async()=>{const next=validateLimits({total:$('#tc-total').value,symbols:{...limits.symbols,[$('#tc-coin').value]:$('#tc-cap').value}});if(loggedIn)await command('limits',{limits:next});limits=next;localStorage.setItem(storageKey,JSON.stringify(limits));invalidate();paintLimits();message(loggedIn?'서버에 전체·종목별 한도를 저장했습니다.':'모의 계산용 한도를 저장했습니다. 실계좌 실행 전 서버에도 저장합니다.');});
for(const field of ['#tc-total','#tc-cap','#tc-equity'])$(field).addEventListener('input',invalidate);
$('#tc-coin').onchange=()=>{market=null;candles=[];decision=null;invalidate();paintLimits();paintComparison();$('#tc-price').textContent='—';$('#tc-prob').textContent='계산 대기';};
$('#tc-strategy').onchange=()=>{invalidate();decision=null;$('#tc-prob').textContent='재계산 대기';};
$('#tc-load').onclick=()=>run(async()=>{
  invalidate();const s=selected();market=await json('/api/exchange?'+new URLSearchParams({exchange,coin:s.coin}));$('#tc-price').textContent=fmt(market.price,futures?3:0);
  let end=Date.now();const map=new Map();
  for(let i=0;i<45;i++) {message(`${name} 완성 일봉 수집 중 · ${map.size}개`);const page=await json('/api/exchange?'+new URLSearchParams({exchange,coin:s.coin,action:'candles',end:String(end)}));if(!page.candles.length)break;for(const c of page.candles)map.set(c.timestamp,c);const first=Math.min(...page.candles.map(c=>c.timestamp));if(first>=end)throw Error('캔들 페이지 반복');end=exchange==='bitget'?first+DAY:first-1;if(map.size>=3500)break;}
  if(selected().coin!==s.coin||selected().strategy!==s.strategy)throw Error('선택이 변경되었습니다. 다시 조회하세요.');
  candles=[...map.values()].sort((a,b)=>a.timestamp-b.timestamp);decision=decide(candles,s.strategy,{initial:true});$('#tc-prob').textContent=percent(decision.probability);
  message(`${decision.explanation} · 표본 ${decision.sample}개 · 완성 일봉 ${candles.length}개 · 마지막 일봉 ${new Date(decision.bar).toLocaleString('ko-KR')} · ${decision.kind}. 확률 80%는 수익 확률이나 수익 보장이 아닙니다.`);
});
$('#tc-preview').onclick=()=>run(async()=>{if(!market||!candles.length)throw Error('거래소 시세·신호를 먼저 조회하세요.');invalidate();const s=selected(),inputLimits=validateLimits({total:$('#tc-total').value,symbols:{...limits.symbols,[s.coin]:$('#tc-cap').value}});decision=decide(candles,s.strategy,{initial:true});market=await json('/api/exchange?'+new URLSearchParams({exchange,coin:s.coin}));const snapshot={...market,equity:$('#tc-equity').value,available:$('#tc-equity').value,positions:[],pending:[],at:Date.now()};const p=makePlan({...s,limits:inputLimits,snapshot,meta:market.meta,decision});planView(p,false);message('모의 계좌 주문 계산입니다. 거래소 주문을 전송하지 않았습니다.');});
$('#tc-login').onclick=()=>run(async()=>{const token=$('#tc-token').value;$('#tc-token').value='';await command('login',{token});await status();message('관리자 접속 완료. 실계좌 잔고로 미리보기를 진행할 수 있습니다.');});
$('#tc-logout').onclick=()=>run(async()=>{await command('logout');loggedIn=false;$('#tc-auto-on').disabled=true;$('#tc-auto-off').disabled=true;$('#tc-auto-state').textContent='자동매매 상태: 관리자 접속 필요';invalidate();$('#tc-private-preview').disabled=true;$('#tc-stop').disabled=true;$('#tc-account').replaceChildren();$('#tc-mode').textContent='로그아웃';message('로그아웃했습니다. 이미 시작한 서버 자동매매는 계속됩니다.');});
$('#tc-refresh').onclick=()=>run(async()=>{await status();message('실행 서버의 최근 상태를 조회했습니다.');});
$('#tc-private-preview').onclick=()=>run(async()=>{invalidate();const next=validateLimits({total:$('#tc-total').value,symbols:{...limits.symbols,[$('#tc-coin').value]:$('#tc-cap').value}});const requestedRevision=revision;const result=await command('preview',{limits:next});if(revision!==requestedRevision)throw Error('입력값이 바뀌었습니다. 실계좌 미리보기를 다시 실행하세요.');quote=result;planView(quote,true);$('#tc-arm').disabled=!server?.enabled;$('#tc-arm').textContent=server?.demo?'거래소 데모 자동매매 시작':'실주문 자동매매 시작';message('서버 잔고로 계산한 미리보기입니다. 30초 이내 시작할 수 있으며 주문 전 한도를 다시 검증합니다.');});
$('#tc-arm').onclick=()=>run(async()=>{if(!quote||Date.now()>quote.expires)throw Error('미리보기가 만료되었습니다. 다시 조회하세요.');const quoteId=quote.id;invalidate();await command('arm',{quoteId});await status();message('자동매매를 등록했습니다. 서버에서 실제 체결·잔량을 확인하세요.');});
$('#tc-stop').onclick=()=>run(async()=>{await command('stop');invalidate();await status();message('선택 종목의 자동매매 중지 및 앱 미체결 취소를 확인했습니다. 보유 포지션은 유지됩니다.');});
json('/api/trading').then(s=>message(s.message)).catch(e=>message('서버 연결 상태 조회 실패: '+e.message));
json(new URL('./comparison.json',import.meta.url)).then(data=>{comparison=data;paintComparison();}).catch(()=>{$('#tc-comparison').textContent='과거 비교 자료를 불러오지 못했습니다.';});
const legacy=document.createElement('p');legacy.className='legacy-data-notice';legacy.textContent='이 아래는 기존 앱의 내장 가격·과거 백테스트 분석 영역입니다. 현재 거래소 주문 조건과 투자 한도는 위 D−5 / 80% 거래 관리에서 적용합니다. 과거 수익률을 코빗·비트겟 실매매 수익률로 해석하지 마세요.';root.insertAdjacentElement('afterend',legacy);

for(const [selector,on] of [['#tc-auto-on',true],['#tc-auto-off',false]])$(selector).onclick=()=>run(async()=>{invalidate();try{await command('automation',{on});await status();message(on?'자동매매 ON. 종목별 실계좌 미리보기 후 시작하세요.':'자동매매 OFF. 이 거래소의 앱 미체결 취소를 확인했습니다. 보유 포지션은 유지됩니다.');}catch(error){try{await status();}catch{}throw error;}});
